### PR TITLE
Resolved #116 Resource leak related the kill cursors

### LINKED ISSUE #116: Possible Resource Leak
It appears as if the `MongoKillCursorsMessage` is being sent with `_Connection.query`. I believe OP_KILL_CURSORS messages don't trigger a response from the db server which leaves completers in the `_replyCompleters` map.

### PR DESCRIPTION
**Pull request by rajmaniar**

### CODE REVIEW

**Comment by Pacane** [comment]
thanks!

**Comment by rajmaniar** [comment]
You're welcome! Thank you for merging so quickly!

**Comment by rajmaniar** [comment]
Does travis automatically deploy to pub? Do we (I) need to bump the version number?

**Comment by Pacane** [comment]
No travis doesn't deploy automagically to pub, and yes we need to bump the version. I'll deploy a new version later today. sorry for the inconvenience

**Comment by rajmaniar** [comment]
No worries! Thanks for all your work on this driver!

**Comment by rajmaniar** [comment]
I haven't seen this pop up in pub yet so I'm just checking in to see how it's going... :)

**Comment by Pacane** [comment]
There you go, sorry about that.

**Comment by rajmaniar** [comment]
No worries, thank you!

**Pull request merged**
