### PR TITLE
Dart 2 compatibility

### PR DESCRIPTION
**Pull request by aemino**
Hello there,

I was trying to use this library with Dart 2 and `--preview-dart-2` enabled, but unfortunately, there were a number of issues.

I've gone through the codebase and gotten all of the tests which failed with `--preview-dart-2` (but not without) to pass.

When I was going through this code, I tried to take a hands-off approach, only fixing what was absolutely necessary.  There are likely many more improvements that can be made—specifically, many generic parameters which are currently omitted, but should likely be specified.

I have also opened a relevant pull request here:
https://github.com/mongo-dart/mongo_dart_query/pull/11

### CODE REVIEW

**Comment by thosakwe** [comment]
Looks like the Travis CI build is failing. I'll look into it.

**Comment by aemino** [comment]
@thosakwe After a bit of fumbling around, I got the build to pass.  I made the false assumption earlier that it was one of the tests causing the CI build to fail.  After actually checking the logs, I realized that it was actually because I was using `List.cast()`, which is a Dart 2-exclusive method.

**Comment by mit-mit** [comment]
Hi @tsander, looks like you are listed as an author on this package. Can you help getting this and https://github.com/mongo-dart/mongo_dart_query/pull/11 reviewed?

**Comment by thosakwe** [comment]
I’ll definitely have a chance to look at this today; I’m a maintainer as well.

**Comment by leocavalcante** [comment]
I'm waiting just this package to upgrade my project to `dev-0.64.1`.
@thosakwe to rescue, again! 🙇

**Comment by thosakwe** [comment]
Thank you so much for the contribution!

However, I don't have publish access for this project yet on Pub.

@vadimtsushko @Pacane @paulecoyote @sestegra @tsander By any chance would any of you be willing to run `pub uploader add thosakwe@gmail.com`? Thanks in advance.

**Comment by thosakwe** [comment]
Note: This build failed after the merge, though the build for the PR itself passed. Not sure if there has been an change in the Dart SDK since then, but:

https://travis-ci.org/mongo-dart/mongo_dart/jobs/397886728

**Comment by aemino** [comment]
@thosakwe I think this may be due to my PR in the `mongo_dart_query` package not yet being merged.  However, if this was the case, I wouldn't have expected the PR build to pass in the first place.  Regardless, merging the other PR should help narrow down the cause.

**Comment by vadimtsushko** [comment]
Hi @thosakwe. Thank you very much for making the effort to support this project. I am really sorry that I  myself currently not able to contribute. 
I have just checked what can be wrong with your publishing rights and discovered that you were not in a list of repository admins. Sorry for that. Sent you an invitation through the gutter pm

**Comment by vadimtsushko** [comment]
https://github.com/mongo-dart/mongo_dart/invitations

**Comment by thosakwe** [comment]
I'm still working on this, in my own fork: https://github.com/thosakwe/mongo_dart

There are more cast errors that have popped up; I'm working on remedying these.

**Pull request merged**
