### PR TITLE
* Dart/Flutter 1.9 compatibility

### PR DESCRIPTION
**Pull request by TobiasHeidingsfeld**
Since updating to Flutter 1.9 /Dart 2.5 mongo_dart does not work due to change in List<int> to Uint8List. Pull request fixes this

### CODE REVIEW

**Comment by Pacane** [comment]
Thank you!

**Comment by Pacane** [comment]
The tests are breaking, can you take a look?

**Comment by TobiasHeidingsfeld** [comment]
added a new commit for failing test´s

**Comment by steve-cahn** [comment]
Is the current solution to downgrade to flutter 1.9.0?

**Comment by thumbert** [comment]
The test that fails is an old issue.  See #120  You can work around it.  But you can't work around this issue if you want to upgrade to Dart 2.5.0.

**Comment by thosakwe** [comment]
@Pacane Am I ok to merge the PR, and publish a patch (with the test fixed)?

**Comment by Pacane** [comment]
Sure!

**Comment by TobiasHeidingsfeld** [comment]
Let me know when the new version is up on pub.dev as I have an package building onto of mongo_dart and will need to update the depedency! Thank you for the great package.

**Comment by a14n** [comment]
Regardless the test issue I believe the right fix is the change I did in #162 because it should be compatible with Dart<2.5 (and is the changes advised by [Dart 2.5 CHANGELOG](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md))

**Comment by thosakwe** [comment]
Resolved, see the discussions at #159, #160, and #162. https://pub.dev/packages/mongo_dart/versions/0.3.6

**Pull request closed without merging**
