### PR TITLE
Complete the update command with ModernMessage

### PR DESCRIPTION
**Pull request by jodinathan**
I particularly needed arrayFilters in the update command, but I ended up
adding all options from https://docs.mongodb.com/manual/reference/command/update/ while changing it to use ModernMessage.

### CODE REVIEW

**Comment by jodinathan** [comment]
fixes https://github.com/mongo-dart/mongo_dart/issues/157

**Comment by giorgiofran** [comment]
Thanks, at present I'm working on the find method and related commands. As soon at possible I will give a look to your request.

**Comment by jodinathan** [comment]
> Thanks, at present I'm working on the find method and related commands. As soon at possible I will give a look to your request.

honestly, this modern message makes creating commands a breeze.
thanks for thee hard work

**Comment by giorgiofran** [comment]
For consistency with all new features, I have added arrayFilters in a different way. You can see it in the last release.

**Comment by giorgiofran** [comment]
I close this request, feel free to open a new issue if needed.

**Pull request closed without merging**
